title:            Luke Deniston
tagline:          Blog of Luke Deniston
description:      Blog of Luke Deniston

owner:
  name:           Luke Deniston
  avatar:         avatar.png
  bio:            "Programmer & Painter"
  email:          luke@lukedeniston.com
  bluesky:        lukedeniston.com
  github:         luketheobscure
  location:       "Fresno, CA"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Books
    url: /books
  - title: Music
    url: /music
  - title: Linkedin
    url: https://www.linkedin.com/in/lukedeniston/
    external: true
  - title: Github
    url: https://github.com/luketheobscure
    external: true

timezone:    America/Los_Angeles
future:      true

permalink:   /:categories/:title

sass:
    sass_dir: assets/sass

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
