title:            Luke Deniston
tagline:          Blog of Luke Deniston
description:      Blog of Luke Deniston

owner:
  name:           Luke Deniston
  avatar:         avatar.png
  bio:            "Programmer & Painter"
  email:          luke@lukedeniston.com
  twitter:        lukedeniston
  github:         luketheobscure
  location:       "Fresno, CA"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Twitter
    url: https://twitter.com/lukedeniston
    external: true
  - title: Github
    url: https://github.com/luketheobscure
    external: true

timezone:    America/Los_Angeles
future:      true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data"]

permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
